name: Run Collector

on:
  schedule:
    - cron: '*/10 * * * *'   # هر 10 دقیقه اجرا شود
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install telethon

      - name: Run script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: python collector.py

      - name: Commit file
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add configs.txt
          git commit -m "update configs" || echo "no changes"
          git push
